#!/bin/bash

# Author: BuffBaby253
# Title: Project Straw
# Description: Captures all nearby WiFi Traffic into PCAP form and saves seperate files to matching networks

echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk:,,:xWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKd:o0NNkclXWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOlckNWWWWWKlc0WWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXx:o0WWWWWWWWWNd:kWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0o:dXWWWWWWWWWWWWWO:oNWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNkclONWWWWWWWWWWWWWWWWKccKWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0d:dKWWWWWWWWWWWWWWWWWWWWNo:kWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWNOlckNWWWWWWWWWWWWWWWWWWWWWWWWx:OWW
WWWWWWWWWWWWWWWWWWWWWWWWWKx:o0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWOlcxXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWXxclOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWW0o:dXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWNkclkNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWKd:dKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWOlcxNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWXxclOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWW0dcdKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWNOllkNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWNdd0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"

echo "What interface do you want to use, wlan1 huh?"

read wlan

echo "How long do you want Project Straw to run? (Input number of seconds)"

read sleep

echo "I will now do as you wish, wait quietly please and thank you"

# Define the output directory
output_dir="captures"

# Create the output directory if it doesn't exist
mkdir -p "$output_dir"

# Start airodump-ng to capture traffic
airodump-ng --write "$output_dir/capture" --output-format pcapng $wlan &

# Wait for a few seconds to allow airodump-ng to capture some data
sleep $sleep

# Parse the captured files and split them by BSSID
for file in "$output_dir/"*.pcapng; do
    bssid=$(tshark -r "$file" -Y wlan.fc.type_subtype==0x08 -T fields -e wlan.bssid | head -n 1)
    if [ -n "$bssid" ]; then
        mv "$file" "$output_dir/$bssid.pcapng"
    else
        rm "$file"
    fi
done

echo "Capture completed. Files saved in $output_dir."
